
# Start fresh from a smaller image
FROM alpine:3.9 
COPY diaginfra /app/
COPY build /app/
# COPY conf/config.yaml /app/conf/
# This container exposes port 3000 to the outside world
EXPOSE 3000
# Run the binary program produced by `go install`
WORKDIR /app
CMD ["diaginfra" "server"]