
stages:
  - golang
  - npm
  - image

golang:
  stage: golang
  image: golang:1.19.6
  script: 
    - go test ./...
    - CGO_ENABLED=0 go build -o diaginfra main.go
  artifacts:
    path:
      - diaginfra
      - conf
    expare_in: 1 day
npm build:
  stage: npm
  image: node:18.15.0-alpine
  script:
    - npm init
    - npm run build
  artifacts:
    path:
      - build
    expare_in: 1 day

create image:
  stage: image
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  dependencies:
    - build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID} -f ./Docker_K8s/Dockerfile_ci .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest