---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag }}
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: vol-config
          mountPath: "/app/conf"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
      volumes:
        - name: vol-config
          configMap:
            name: diag-config

