---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag }}
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}

